#!/usr/bin/env ruby
# frozen_string_literal: true

require 'rubygems'
require 'bundler/setup'
require 'kaiser_ruby'
require 'kaiser_ruby/cli'
require 'kaiser_ruby/refinements'

KaiserRuby::CLI.start(ARGV)
